version: "3.9"
services:
  aerospike:
    image: aerospike/aerospike-server:latest
    networks:
      - aerospikenetwork
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
    labels:
      com.github.vlsidlyarevich.pepe.description: "Docker compose stack for pepe chat"
    command: [ "--config-file","/run/secrets/aerospike.conf" ]
    secrets:
      - source: conffile_v1
        target: aerospike.conf
        mode: 0440

networks:
  aerospikenetwork:
    driver: overlay
    attachable: true

secrets:
  conffile_v1:
    file: ./aerospike.conf

